security:
  user:
    name: edison
    password: radar
  ignored:
  - "*.bundle.*"
logging:
  level:
    org.springframework.security: DEBUG
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    
    